### ISSUE TITLE
Request to collapse result/output alone in notebooks

### ISSUE THREAD

**Issue by sharan19** [fastai/nbdev_template#12]
I am trying to scrap images from internet for building a image classifier using fastai. I am trying with some large number of images. This is making result longer and it is not useful for the viewer. 
Would love to have an option just to colapse the results alone and not the code with it.
![Current](https://user-images.githubusercontent.com/40206793/77991237-ebd61b00-7340-11ea-890a-e997c51dd96b.png)

**Comment by sgugger** [comment]
You can either tag your cell with `#hide_output` or put the cell in collapsed mode (might need the collapsible headers extension). Both will hide the output for the doc rendering.

If your issue is with fastpages, you should open it there, as I'm not super familiar with the collapsible code they added.

**Comment by sharan19** [comment]
Hi i want only the output to be colapsable. Hiding it will confuse lot of beginners like me. This will give the viewer the option to decide how to proceed.
I raised this request previously in fast pages but Hamel asked me to post this here.

**Comment by sgugger** [comment]
Mmmmm, @hamelsmu what is needed to be changed in nbedv_template for this?

**Comment by hamelsmu** [comment]
We would have to edit [`hide.tpl`](https://github.com/fastai/nbdev/blob/master/nbdev/templates/hide.tpl) 

I can try to give this a shot

**Comment by hamelsmu** [comment]
Looks like this functionality is already in nbdev?  Found this.  Will test and confirm

```
{%- if cell.metadata.hide_output -%}
{%- else -%}
    {{ super()  }}
{%- endif -%}
{% endblock output_group %}
```

**Comment by hamelsmu** [comment]
I'm opening a PR now

**Comment by hamelsmu** [comment]
Oh you want it to be collapsable?  🤦‍♂ ayeyay I missed that

**Comment by hamelsmu** [comment]
Ok I crafted a PR that implements this feature request: https://github.com/fastai/nbdev/pull/119/files
