### ISSUE TITLE
make docs_serve is not working

### ISSUE THREAD

**Issue by KushajveerSingh** [fastai/nbdev_template#16]
When running `make docs_serve` I get the following error `Makefile:10: *** missing separator.  Stop.`.

I can run `cd docs && bundle exec jekyll serve`. I have a dev install of nbdev. On googling this issue I came across this [post](https://stackoverflow.com/questions/16931770/makefile4-missing-separator-stop) which says the issue is due to Makefile using tabs instead of spaces.

**Comment by sgugger** [comment]
There is no Makefile file in `nbdev_template` so this issue should be in nbdev. The bug was introduced by a recent PR using four spaces instead of a tab, should be fixed now (you'll need to delete you Makefile to have it autogenerated again, after pulling the latest of nbdev).

**Comment by dsm-72** [comment]
@sgugger it says 

```
make docs_serve        
cd docs && bundle exec jekyll serve
bundler: command not found: jekyll
Install missing gem executables with `bundle install`
make: *** [Makefile:15: docs_serve] Error 127


```

it seems docker file is messed up?
