### ISSUE TITLE
How to fix 'Unintended read access in kramdown gem'

### ISSUE THREAD

**Issue by JiaxiangBU** [fastai/nbdev_template#19]
I receive the GitHub Official Email that mentions, I own three repositories exposed to 'Unintended read access in kramdown gem'.

I build all of the three from nbdev_template, here are the alert messages,

* [Alerts · JiaxiangBU/dynamic_topic_modeling](https://github.com/JiaxiangBU/dynamic_topic_modeling/network/alert/docs/Gemfile.lock/kramdown/open)
* [Alerts · JiaxiangBU/conversion_metrics](https://github.com/JiaxiangBU/conversion_metrics/network/alert/docs/Gemfile.lock/kramdown/open)
* [Alerts · JiaxiangBU/pyks](https://github.com/JiaxiangBU/pyks/network/alert/Gemfile.lock/kramdown/open)

I  update the 'docs/Gemfile.lock' from the latest nbdev_template, but the alert doesn't disappear. 

1. https://github.com/JiaxiangBU/pyks/commit/d23761b101fd234aa606fee3c05055fc768c5cd3

I do not know much about gem, any suggestion for me, could I just ignore the sort of message?

**Comment by gimseng** [comment]
same here

**Comment by JiaxiangBU** [comment]
> same here

I fix it manually https://github.com/JiaxiangBU/dynamic_topic_modeling/commit/22e11d85f15de4bfc9707095fb3762c3d3c5c047 and the alert does not appear anymore. But I am not sure whether the package building process is OK with the higher version requirement of kramdown.
