### ISSUE TITLE
nbdev tutorial fails with new template

### ISSUE THREAD

**Issue by migueltorres** [fastai/nbdev_template#34]
I have started a new repo following the tutorial, and running nbdev_build_lib fails with a FileNotFoundError exception trying to access \docs\_data\topnav.yml

That file is missing in the nbdev_template and I think is related to the new theme-based version. The helper script is not mentioned on the nbdev tutorial, and the basic procedure for creating a new nbdev repo is broken. If this template is going to be the default behaviour I think it should be reflected in the tutorial and tools (nbdev_new also leads to the same problem). If this is still an optional thing then maybe it shoud be in another branch so the regular procedure still works.

**Comment by migueltorres** [comment]
Updating nbdev on my computer fixes the issue (I had 1.1.5). Maybe to avoid this in the future we sould match nbdev version with specitic nbdev_template tag instead of pointing to the latest master branch commit?

**Comment by hamelsmu** [comment]
Correct, the tutorial assumes you are using the latest version of nbdev.

**Comment by TejasAvinashShetty** [comment]
Maybe one could set up a script that tests the template each time a commit is made to see if everything still works fine.
@hamelsmu @jph00 @sgugger
