### ISSUE TITLE
source 404

### ISSUE THREAD

**Issue by TejasAvinashShetty** [fastai/nbdev_template#36]
*Describe the bug**
Clicking on the source code in the  documentation website causes 404 error

**To Reproduce**

1. made a [project](https://github.com/TejasAvinashShetty/deck_of_cards) using the template all the way to set up the [documentation](https://tejasavinashshetty.github.io/deck_of_cards/card.html)
2. Click on the Source link for any piece of code

**Expected behavior**
lead to source code

**Screenshots**
![Screenshot from 2021-01-31 11-18-40](https://user-images.githubusercontent.com/27445854/106375890-199f4c80-63b6-11eb-8e27-aeb1f090aabe.png)

![Screenshot from 2021-01-30 13-59-38](https://user-images.githubusercontent.com/27445854/106351629-6aa23880-6303-11eb-9497-11c37a68a573.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [ chrome]
 - Version [88]

**Comment by TejasAvinashShetty** [comment]
**Additional context**
I think the error is because it shows 
[deck_of_cards/tree/Master/deck_of_cards/card.py#L7](https://github.com/TejasAvinashShetty/deck_of_cards/tree/Master/deck_of_cards/card.py#L7).
instead of
[deck_of_cards/blob/master/deck_of_cards/card.py#L7](https://github.com/TejasAvinashShetty/deck_of_cards/blob/master/deck_of_cards/card.py#L7)

**Comment by hamelsmu** [comment]
This is an erroneous issue as you spelled `Master` should be `master`
