### ISSUE TITLE
homepage headache

### ISSUE THREAD

**Issue by TejasAvinashShetty** [fastai/nbdev_template#40]
Unfortunately, @hamelsmu it seems that [change tree to blob](https://github.com/fastai/nbdev_template/pull/37) causes the homepage link for the project on PyPI to be displayed wrongly
For example [in ihu](https://github.com/TejasAvinashShetty/ihu/issues/4)

https://pypi.org/project/ihu/
![image](https://user-images.githubusercontent.com/27445854/106566586-7f2a3f00-6556-11eb-8fc0-19d93341cedf.png)
https://github.com/TejasAvinashShetty/ihu/blob/master/
leads to 404

the old git_url parameter works well here 
https://github.com/TejasAvinashShetty/ihu/tree/master/ leads to the correct page.

Sorry for creating this trouble

**Comment by TejasAvinashShetty** [comment]
probably one needs to make a separate pypi_url parameter. 
But maybe that would complicate stuff
🤔

**Comment by hamelsmu** [comment]
Closed by https://github.com/fastai/nbdev_template/pull/41

Also the tree URL redirects to blob automatically.  I'm not sure why you are getting a dead end?

**Comment by TejasAvinashShetty** [comment]
The tree URL does not redirect at least not here.

[deck_of_cards/tree/Master/deck_of_cards/card.py#L7](https://github.com/TejasAvinashShetty/deck_of_cards/tree/Master/deck_of_cards/card.py#L7).
instead of
[deck_of_cards/blob/master/deck_of_cards/card.py#L7](https://github.com/TejasAvinashShetty/deck_of_cards/blob/master/deck_of_cards/card.py#L7)
