### ISSUE TITLE
The tree URL does not redirect at least not here.

### ISSUE THREAD

**Issue by TejasAvinashShetty** [fastai/nbdev_template#43]
The tree URL does not redirect at least not here.

[deck_of_cards/tree/Master/deck_of_cards/card.py#L7](https://github.com/TejasAvinashShetty/deck_of_cards/tree/Master/deck_of_cards/card.py#L7).
instead of
[deck_of_cards/blob/master/deck_of_cards/card.py#L7](https://github.com/TejasAvinashShetty/deck_of_cards/blob/master/deck_of_cards/card.py#L7)

_Originally posted by @TejasAvinashShetty in https://github.com/fastai/nbdev_template/issues/40#issuecomment-779679490_

**Comment by hamelsmu** [comment]
Right, but your branch name is malformed.  `Master` -> `master`.  

This is not an actual issue 

for example this page  https://fastai.github.io/deck_of_cards/card.html#Card -> 
https://github.com/fastai/deck_of_cards/tree/master/deck_of_cards/card.py#L15
