### ISSUE TITLE
Use of other Jekyll templates

### ISSUE THREAD

**Issue by HDavidEspinosa** [fastai/nbdev_template#48]
Is there a way to load or edit the jekyll-theme used by the template?

**Comment by HDavidEspinosa** [comment]
I just realised that, when using docstrings in [Numpydoc format](https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format), the `nbdev_build_docs` adds the Parameters, Results and Raises, that are underlined in the docstrings to h2 headings in the docs' HTML.

Is there a way to automated so that this format becomes h5 headings?

I have a feeling this can be linked to this nbdev issue. 

> https://github.com/fastai/nbdev/issues/318

**Comment by hamelsmu** [comment]
No there isn't a way to do this with Jekyll, currently.  

Also please try to keep issues relevant to a single concern.  Your comment about docstrings is interesting, however please feel free to open a new issue about that particular situation if necessary.

**Comment by HDavidEspinosa** [comment]
Thanks for your answer and your work.

You are right about my second concern. I apologise.
