### ISSUE TITLE
nbdev_build_lib error with _config.yml not found - when following "Getting Started" directions

### ISSUE THREAD

**Issue by paulkarayan** [fastai/nbdev_template#6]
following the directions here:
https://nbdev.fast.ai/#Getting-Started

after cloning the template repo and editing settings.ini, I attempted to run the command:
➜  pk_nbdev git:(master)  nbdev_build_lib

expected behaviour:
- runs without error. 
- predicate actions, such as creating a new dir with project name, are taken.

actual behaviour:
error message displayed:
```
Traceback (most recent call last):
  File "/usr/local/bin/nbdev_build_lib", line 8, in <module>
    sys.exit(nbdev_build_lib())
  File "/usr/local/lib/python3.7/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/usr/local/lib/python3.7/site-packages/nbdev/cli.py", line 20, in nbdev_build_lib
    notebook2script(fname=fname)
  File "/usr/local/lib/python3.7/site-packages/nbdev/export.py", line 364, in notebook2script
    update_baseurl()
  File "/usr/local/lib/python3.7/site-packages/nbdev/export.py", line 351, in update_baseurl
    with open(fname, 'r') as f: code = f.read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/paulkarayan/nbdev/docs/_config.yml'
[1]    21176 exit 1     nbdev_build_lib
```
but at least some things, like the directory named after your project name in settings.ini, are created correctly.

-- 
in searching your code, i'm guessing maybe you've changing from 
_config.yml -> settings.ini 

and we're getting hung up here:
https://github.com/fastai/nbdev/blob/master/nbdev/export.py#L349

let me know if i can help fix. kudos thus far!!

**Comment by paulkarayan** [comment]
workaround:
created  <project_name>/docs/_config.yml

➜  nbdev git:(master) ✗ nbdev_build_lib
Converted 00_core.ipynb.
Converted index.ipynb.

and it appears to populate the _config.yml

**Comment by paulkarayan** [comment]
I have a patch to provide this workaround, if you can provide push access or a description of how you'd like this submitted...

**Comment by sgugger** [comment]
It's just a matter of inverting two instructions in `nbdev_build_lib`. Will do and add a sanity check. Closing this issue as this is inside `nbdev`, not the template.

**Comment by enryH** [comment]
I now had to manually create the folder `./docs/_data` to follow along the `nbdev_build_lib` [step in the tutorial](https://nbdev.fast.ai/tutorial.html#Build-lib). Otherwise I got the following error:

```python
FileNotFoundError: [Errno 2] No such file or directory: './nbdev_tutorial_project/docs/_data/topnav.yml'
```

**Comment by ctwardy** [comment]
Yes, I got the same issue as enryH.  

Possibly relevant: I had created my repo using `nbdev_new`.

**Comment by lazarillo** [comment]
So far, `nbdev` seems quite nice, but the fact that the tutorial does not work makes me a little nervous of the claim that `nbdev` makes it *easier* to ensure that documentation + code are always in sync and that `nbdev` provides the "literate programming" environment.
