### ISSUE TITLE
How to publish to pypi?

### ISSUE THREAD

**Issue by the21st** [fastai/nbdev_template#60]
Hi! I'm following the "nbdev live coding with Hamel Husain" [video](https://www.youtube.com/watch?v=ZJTop5uqC2U&t=1453s) and at the 43:53 mark, Hamel does `make pypi` but there's no Makefile in this template. Is there any reason for that?

**Comment by hamelsmu** [comment]
The makefile will appear once you actually materialize your repository and use `nbdev_build_lib` and `nbdev_build_docs`
