### ISSUE TITLE
No Makefile provided in template

### ISSUE THREAD

**Issue by Torvaney** [fastai/nbdev_template#80]
There's no Makefile provided in this template despite the Readme suggesting otherwise:

> You can run the command `make docs_serve` from the root of your repo to serve the documentation locally after calling `nbdev_build_docs` to generate the docs.

This is relatively straightforward to workaround by copying the Makefile from https://github.com/fastai/nbdev. Should it be included in the first place?

**Comment by d2weber** [comment]
I was running in the same Issue after following the (nbdev tutorial)[https://nbdev.fast.ai/tutorial.html].

I had to run 
```
nbdev_build_docs
(cd docs && bundler install)
```
then the Makefile should have been generated and `make docs_serve` should work. Not sure how the workflow is supposed to be..

**Comment by d2weber** [comment]
It is described in https://nbdev.fast.ai/tutorial.html#View-docs-locally

**Comment by Torvaney** [comment]
Ah, okay - it doesn't explicitly say that this is required to pull in the Makefile, but the link is clear. Thanks
