### ISSUE TITLE
nbdev_clean_notebooks issue? 

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev_template#95]
I run this before I push, when the CI runs it fails. How do I fix?
```
  echo "Check we are starting with clean git checkout"
  if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
  echo "Trying to strip out notebooks"
  nbdev_clean_nbs
  echo "Check that strip out was unnecessary"
  git status -s # display the status to see which nbs need cleaning up
  if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_git_hooks"; false; fi
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.15/x64
Check we are starting with clean git checkout
git status is not clean
```

**Comment by dsm-72** [comment]
@muellerzr any idea? Also sidebar not showing on GitHub Pages.

**Comment by dsm-72** [comment]
@hamelsmu ? any idea

**Comment by dsm-72** [comment]
@muellerzr any update?

**Comment by hamelsmu** [comment]
Not able to reproduce the error from the way the issue was communicated.

Here is a blog article that describes a framework for reporting bugs more effectively that others can act on: http://testthewebforward.org/docs/bugs.html

**Comment by dsm-72** [comment]
@hamelsmu  I am asking for how to fix this. How to reproduce this? Easy.

1. fork template
2. update config to match your project (e.g. settings)
3. `nbdev_build_lib && nbdev_build_docs`
4. push to get
5.  get this error

**Comment by dsm-72** [comment]
yes I have tried this with toy repos. Using even the tutorial `Card` code yields this

**Comment by hamelsmu** [comment]
DID you install git hooks?  Did you follow all the instructions?

**Comment by dsm-72** [comment]
@hamelsmu  yes I did. I have even made several "toy" examples following the tutorials as outlined on the website all with the same result.

**Comment by dsm-72** [comment]
@hamelsmu any idea how I might deal with this then? I literally can just fork the tutorial repo, fill in the ini settings, and push to GitHub to get these errors and I don't know how to resolve them.
