### ISSUE TITLE
github pages doesn't show navigation

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev_template#96]
Don't know what is going on. On macOS make docs_serve works fine (except in safari), but not pages...

**Comment by dsm-72** [comment]
@hamelsmu ? on github pages the rendering is broken

**Comment by dsm-72** [comment]
@muellerzr any update?

**Comment by hamelsmu** [comment]
Not able to reproduce the error from the way the issue was communicated.  

Here is a blog article that describes a framework for reporting bugs more effectively that others can act on:  http://testthewebforward.org/docs/bugs.html
